chore: update .gitignore and GoReleaser workflow (#39)
* chore: update .gitignore and GoReleaser workflow

- Added `.vscode/settings.json` to .gitignore to prevent IDE-specific settings from being tracked.
- Removed conditional checks for tag references in the GoReleaser workflow to allow execution on all branches.

Signed-off-by: Alessandro De Blasis <alex@deblasis.net>

* chore: enhance GoReleaser workflow to handle tag extraction and version update

- Added a step to extract the target tag name from GITHUB_REF, ensuring proper versioning for npm publishing.
- Implemented logic to update package.json version based on the extracted tag, facilitating automated version management.

Signed-off-by: Alessandro De Blasis <alex@deblasis.net>

---------

Signed-off-by: Alessandro De Blasis <alex@deblasis.net>

diff --git a/.github/workflows/goreleaser.yml b/.github/workflows/goreleaser.yml
--- a/.github/workflows/goreleaser.yml
+++ b/.github/workflows/goreleaser.yml
@@ -64,7 +64,6 @@ jobs:
   publish-npm:
     needs: goreleaser
     runs-on: ubuntu-latest
-    if: startsWith(github.ref, 'refs/tags/') # Run only for tags
     permissions:
       contents: read
       id-token: write
@@ -84,6 +83,27 @@ jobs:
           node-version: "20"
           registry-url: "https://registry.npmjs.org"
 
+      - name: Get Target Tag Name
+        id: get_target_tag
+        # Extracts the tag name from the GITHUB_REF
+        run: |
+          TARGET_TAG=""
+          if [[ "${{ github.ref_type }}" == "tag" ]]; then
+            echo "Using tag from GITHUB_REF: ${{ github.ref_name }}"
+            TARGET_TAG="${{ github.ref_name }}"
+          else
+            # Handle cases where it's not a tag push (e.g., workflow_dispatch for testing)
+            # You might want to add logic here if you need to test publish-npm manually
+            echo "Error: Cannot determine target tag. Not a tag push."
+            exit 1
+          fi
+          echo "TAG_NAME=${TARGET_TAG}" >> $GITHUB_OUTPUT
+          echo "TAG_NAME_NO_V=${TARGET_TAG#v}" >> $GITHUB_OUTPUT
+
+      - name: Update package.json version
+        # Updates the version in package.json to match the git tag
+        run: npm version --no-git-tag-version ${{ steps.get_target_tag.outputs.TAG_NAME_NO_V }}
+
       - name: Install Node.js dependencies for publish script
         run: npm install
 
@@ -98,7 +118,6 @@ jobs:
     name: Update Winget PR Manifest
     needs: goreleaser
     runs-on: ubuntu-latest
-    if: success() && startsWith(github.ref, 'refs/tags/') # Run only on tag success
     steps:
       - name: Get Target Tag Name
         id: get_target_tag
